version: '3.6'
services:
  db:
    env_file:
      - .env
    image: mariadb:latest
    ports:
      - '3308:3306'
    volumes:
      - .local/etc/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  openapi:
    build:
      args:
        - HOST_USER=${HOST_USER}
      context:
        openapi
    command: ['run']
    depends_on:
      - db
    env_file:
      - .env
    image: openapi:latest
    links:
      - db:db
    ports:
      - ${PORT}:${PORT}
